### PR TITLE
Add RxNearby, RxPalette

### PR DESCRIPTION
**Pull request by FranciscoE-Hudl**

### CODE REVIEW

**Comment by zsoltk** [comment]
Thanks for the commit!

RxNearby does not seem to hit the minimum quality you would expect from a library. No decent README with usage example, no url to download it from. Seems pretty young and raw. The lib idea seems cool though. I'd like to see it mature and get back to it later.

On the other hand, I'll happily merge RxPalette.

Cheers,
Zsolt

**Comment by FranciscoE-Hudl** [comment]
Man, you always make me change my PRs hahaha I'll come back with them later, maybe.

**Comment by zsoltk** [comment]
Yeah, I know :D I hope no hard feelings though?

In the meantime, I'll update the contributions guideline.

**Comment by johnjohndoe** [comment]
How about creating issues for missing README, etc?

**Comment by FranciscoE-Hudl** [comment]
@zsoltk None at all :+1: Let's do it.

**Pull request closed without merging**
